id: I708742C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:36:54+00:00'
last_modified: '2022-06-07T21:53:20.185527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23669
  title: བོད་རང་སྐྱོང་ལྗོངས་སློབ་ཆུང་ཚོད་ལྟའི་སློབ་དེབ། སྐད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    128F:
      image_group_id: I1KG23694
      title: ''
      total_pages: 94
      order: 1
      base_file: 128F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
