id: P004310
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:09:36.954421
source_metadata:
  id: bdr:W1KG23669
  title: བོད་རང་སྐྱོང་ལྗོངས་སློབ་ཆུང་ཚོད་ལྟའི་སློབ་དེབ། སྐད་ཡིག
  author: ''
  volumes:
    0a1b666a999a4113b3cd40e3d15beb38:
      image_group_id: I1KG23694
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
